
services:
 vector-db:
  image: qdrant/qdrant
  ports:
    - "6333:6333" 
  

#docker compose up -d
# go to langchain loader -> py pdf(forpdf load )
#%pip install -qU langchain-community pypdf
# what is langchain -> library to build LLM applications provide utils to work with LLMs and vector databases

